version: '3.5'

volumes:
  inway_cert:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  outway_cert:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  docs:
    build:
      context: .
      dockerfile: docs/Dockerfile
      target: build
    volumes:
      - $GOPATH/src/github.com/VNG-Realisatie/nlx:/go/src/github.com/VNG-Realisatie/nlx
    ports:
      - '1313:1313'
    command: hugo server --bind 0.0.0.0

  ca:
    build:
      context: .
      dockerfile: unsafe-ca/Dockerfile
    ports:
      - '8888:8888'
    working_dir: /ca
    command: ./start-ca.sh nlx.local

  inway_cert:
    build:
      context: .
      dockerfile: unsafe-ca/Dockerfile
    depends_on:
      - ca
    volumes:
      - inway_cert:/inway_cert
    command: >
      /bin/ash -c "
        cd /inway_cert &&
        /ca/generate-cert.sh inway.nlx.local DemoProviderOrganization ca &&
        touch /inway_cert/.done
      "

  inway:
    build:
      context: .
      dockerfile: inway/Dockerfile
      target: build
    depends_on:
      - inway_cert
    networks:
      default:
        aliases:
          - inway.nlx.local
    environment:
      - TLS_NLX_ROOT_CERT=/inway_cert/nlx_root.pem
      - TLS_ORG_CERT=/inway_cert/inway_nlx_local.pem
      - TLS_ORG_KEY=/inway_cert/inway_nlx_local-key.pem
    volumes:
      - inway_cert:/inway_cert
      - $GOPATH/src/github.com/VNG-Realisatie/nlx:/go/src/github.com/VNG-Realisatie/nlx
    ports:
      - '2018:2018'
    command: >
      /bin/ash -c "
        while [ ! -f /inway_cert/.done ]; do
          sleep .2
        done
        modd
      "

  outway_cert:
    build:
      context: .
      dockerfile: unsafe-ca/Dockerfile
    depends_on:
      - ca
    volumes:
      - outway_cert:/outway_cert
    command: >
      /bin/ash -c "
        cd /outway_cert &&
        /ca/generate-cert.sh outway.nlx.local DemoRequesterOrganization ca &&
        touch /outway_cert/.done
      "

  outway:
    build:
      context: .
      dockerfile: outway/Dockerfile
      target: build
    depends_on:
      - outway_cert
    networks:
      default:
        aliases:
          - outway.nlx.local
    environment:
      - TLS_NLX_ROOT_CERT=/outway_cert/nlx_root.pem
      - TLS_ORG_CERT=/outway_cert/outway_nlx_local.pem
      - TLS_ORG_KEY=/outway_cert/outway_nlx_local-key.pem
    volumes:
      - outway_cert:/outway_cert
      - $GOPATH/src/github.com/VNG-Realisatie/nlx:/go/src/github.com/VNG-Realisatie/nlx
    ports:
      - '12018:12018'
    command: >
      /bin/ash -c "
        while [ ! -f /outway_cert/.done ]; do
          sleep .2
        done
        modd
      "
