title = "NLX Documentation"
theme = "nlx"
languageCode = "en-us"
baseURL = "https://docs.nlx.io/"
DefaultContentLanguage = "en"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.docs]]
  name = "Functional design"
  weight = 1
  identifier = "functional"
  url = "/functional-design/"

[[menu.docs]]
  name = "Developing on NLX"
  weight = 5
  identifier = "development"
  url = "/development/"
