title = "NLX Documentation"
theme = "nlx"
languageCode = "en-us"
baseURL = "https://docs.nlx.io/"
DefaultContentLanguage = "en"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.docs]]
  name = "Introduction"
  weight = 1
  identifier = "introduction"
  url = "/"

[[menu.docs]]
  name = "Developing on NLX"
  weight = 2
  identifier = "developing-on-nlx"
  url = "/developing-on-nlx/"

[[menu.docs]]
  name = "Contributing to NLX"
  weight = 3
  identifier = "contributing-to-nlx"
  url = "/contributing-to-nlx/"
